dataset_path: LIME-DATA/textvqa
task: textvqa_suit_val_vd
test_split: train
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.textvqa_aggregate_submissions
    higher_is_better: true
include: _default_template_textvqa_yaml
